export enum ACTION_TYPES {
  SIGN_IN = 'SIGN_IN',
  SUCCESS_TO_SIGN_IN = 'SUCCESS_TO_SIGN_IN',
  UPLOAD_IMAGES = 'UPLOAD_IMAGES',
  START_TO_UPLOAD_IMAGES = 'START_TO_UPLOAD_IMAGES',
  SUCCEED_TO_UPLOAD_IMAGES = 'SUCCEED_TO_UPLOAD_IMAGES',
  FAIL_TO_UPLOAD_IMAGES = 'FAIL_TO_UPLOAD_IMAGES',
  START_TO_UPDATE_DB = 'START_TO_UPDATE_DB',
  SUCCEED_TO_UPDATE_DB = 'SUCCEED_TO_UPDATE_DB',
  FAIL_TO_UPDATE_DB = 'FAIL_TO_UPDATE_DB',
  FETCH_IMAGES = 'FETCH_IMAGES',
}
